lane :build_appstore do

  xcversion(version: "12.4")
  gym(
    scheme: "NerdSummit",
    configuration: "Release",
    output_directory: "./build/app-store",
    clean: true,
    export_options: "./config/AppStoreConfiguration.plist",
    output_name: "NERDSummit.ipa"
  )

end

lane :build_adhoc do
  xcversion(version: "12.4")
  gym(
    scheme: "NerdSummit",
    configuration: "Release",
    output_directory: "./build/ad-hoc",
    clean: true,
    export_options: "./config/AdHocConfiguration.plist",
    output_name: "NERDSummit.ipa"
  )

end

lane :unit_tests do
  xcversion(version: "12.4")

  run_tests(scheme: "NerdSummit")
end

lane :upload_binary do
  upload_to_testflight(
    username: "lfranco@greenwave-solutions.com",
    ipa: "./build/app-store/NERDSummit.ipa",
    team_id: "159005"
  )
end